language: android
android:
  components:
    - tools
    - platform-tools
    - tools

    - build-tools-29.0.3
    - android-29

  licenses:
    - 'android-sdk-license-.+'
    - 'android-sdk-preview-.+'
    - 'google-gdk-license-.+'

before_install:
  - yes | sdkmanager --licenses

script:
  - ./gradlew check